# Configurações comuns a todos os perfis
spring.application.name=backend

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Perfil padrão ao rodar localmente (mvn spring-boot:run)
spring.profiles.default=dev
